// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ajea6eLXDIZp5Dief2u4B3rXNBMb12A',
    appId: '1:791381472975:web:9195fd98a3244b3f5869ba',
    messagingSenderId: '791381472975',
    projectId: 'devpath-36af9',
    authDomain: 'devpath-36af9.firebaseapp.com',
    storageBucket: 'devpath-36af9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa88GaEpxdZNKD-WnbOvGLfbWKIa36ggE',
    appId: '1:791381472975:android:ca2a8a9eef7e84dd5869ba',
    messagingSenderId: '791381472975',
    projectId: 'devpath-36af9',
    storageBucket: 'devpath-36af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMObQAeMKK2cZMFvIZEkheP69Wru0b_jg',
    appId: '1:791381472975:ios:8104d1ff4e8dd02b5869ba',
    messagingSenderId: '791381472975',
    projectId: 'devpath-36af9',
    storageBucket: 'devpath-36af9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMObQAeMKK2cZMFvIZEkheP69Wru0b_jg',
    appId: '1:791381472975:ios:8104d1ff4e8dd02b5869ba',
    messagingSenderId: '791381472975',
    projectId: 'devpath-36af9',
    storageBucket: 'devpath-36af9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Ajea6eLXDIZp5Dief2u4B3rXNBMb12A',
    appId: '1:791381472975:web:c36227ab44ccfbda5869ba',
    messagingSenderId: '791381472975',
    projectId: 'devpath-36af9',
    authDomain: 'devpath-36af9.firebaseapp.com',
    storageBucket: 'devpath-36af9.firebasestorage.app',
  );
}
